### ISSUE TITLE
Run Error on raspi5

### ISSUE THREAD

**Issue by tannal** [artyomd/GPU-Playground#5]
```bash
tannal@raspi:~/tannalwork/projects/GPU-Playground$ ./build/src/playground 
[2024-04-27 14:52:06.396] [debug] instance version queried 1.3.250
[2024-04-27 14:52:08.744] [debug] 
GPU device: V3D 7.1.7 (id: 1433410611, type: integrated, api version: 1.2.255)
GPU driver: V3DV Mesa (id: 19, version: 96477185, conformance version:1.3.6.1, info: Mesa 23.2.1-1ubuntu3.1)

[2024-04-27 14:52:08.864] [error] call failed with error -0x2 /home/tannal/tannalwork/projects/GPU-Playground/src/application/application.cpp:451
```

**Comment by artyomd** [comment]
You are getting an OOM during the swap chain creation. I never tested this project on any resource-constrained environment, and  I am not sure if there is room for memory efficacy improvement during the swap chain creation. That was never the goal of this project, but feel free to submit a pull request with any improvements you find. Also, it may be because of the GPU memory configuration on your rpi. Please ensure the device has enough GPU memory for what you are trying to do. I am not familiar with the rpi, but you can try running the `vkvia` tool to get a full report for the Vulkan device.

**Comment by tannal** [comment]
I got it running on my laptop. I'm using mesa3d not proprietary driver on the rpi which might be a problem.Thanks for your explaination.
